// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.

using System.Runtime.InteropServices;
using CppAst.CodeGen.CSharp;
using Zio;
using Zio.FileSystems;

namespace CppAst.CodeGen.Tests;

public class CSharpModelDumpTests
{
    [Test]
    public void GeneratedFileWritesAutoGeneratedHeaderAndFileScopedNamespaceToConfiguredPath()
    {
        var fileSystem = new MemoryFileSystem();
        var file = new CSharpGeneratedFile((UPath)"/interop/native.cs");
        var @namespace = new CSharpNamespace("Demo.Native") { IsFileScoped = true };
        @namespace.Members.Add(new CSharpClass("Native"));
        file.Members.Add(@namespace);

        file.DumpTo(GeneratedCodeTestHelper.CreateWriter(fileSystem));
        var text = GeneratedCodeTestHelper.NormalizeLineEndings(fileSystem.ReadAllText((UPath)"/interop/native.cs"));

        GeneratedCodeTestHelper.AssertContainsAll(text,
            "// <auto-generated>",
            "namespace Demo.Native;\n\npublic partial class Native;");
    }

    [Test]
    public void TypeWithMembersDumpsGenericsFieldsPropertiesMethodsAndContextualAttributes()
    {
        var typeParameter = new CSharpGenericParameterType("T");
        typeParameter.WhereClauses.Add(new CSharpWhereClause("unmanaged"));

        var native = new CSharpClass("Native")
        {
            Visibility = CSharpVisibility.Internal,
            Modifiers = CSharpModifiers.Static | CSharpModifiers.Unsafe | CSharpModifiers.Partial,
        };
        native.GenericParameters.Add(typeParameter);
        native.BaseTypes.Add(new CSharpFreeType("global::System.IDisposable"));
        native.Members.Add(new CSharpField("name")
        {
            FieldType = new CSharpFixedArrayType(CSharpPrimitiveType.Byte(), 16),
        });
        native.Members.Add(new CSharpProperty("Handle")
        {
            ReturnType = CSharpPrimitiveType.IntPtr(),
            Visibility = CSharpVisibility.Public,
            GetterOnly = true,
        });

        var returnType = new CSharpTypeWithAttributes(CSharpPrimitiveType.Bool());
        returnType.Attributes.Add(new CSharpMarshalAsAttribute(UnmanagedType.U1));
        var stringParameterType = new CSharpTypeWithAttributes(CSharpPrimitiveType.String());
        stringParameterType.Attributes.Add(new CSharpMarshalAsAttribute(UnmanagedType.LPUTF8Str));
        var open = new CSharpMethod("Open")
        {
            ReturnType = returnType,
            Modifiers = CSharpModifiers.Static | CSharpModifiers.Partial,
        };
        open.Parameters.Add(new CSharpParameter(stringParameterType, "path"));
        native.Members.Add(open);

        var text = GeneratedCodeTestHelper.DumpToString(native);

        GeneratedCodeTestHelper.AssertContainsAll(text,
            "internal static unsafe partial class Native<T> : global::System.IDisposable where T : unmanaged",
            "public fixed byte name[16];",
            "public nint Handle { get; }",
            "[return:global::System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]\n    public static partial bool Open([global::System.Runtime.InteropServices.MarshalAs(UnmanagedType.LPUTF8Str)] string path);");
    }

    [Test]
    public void StructInterfaceAndEnumDumpExpectedDeclarations()
    {
        var @namespace = new CSharpNamespace("Demo");
        @namespace.Members.Add(new CSharpStruct("Value"));
        @namespace.Members.Add(new CSharpInterface("IApi"));
        var mode = new CSharpEnum("Mode") { IsFlags = true };
        mode.BaseTypes.Add(CSharpPrimitiveType.Int());
        mode.Members.Add(new CSharpEnumItem("None", "0"));
        mode.Members.Add(new CSharpEnumItem("Read", "1"));
        @namespace.Members.Add(mode);

        var text = GeneratedCodeTestHelper.DumpToString(@namespace);

        GeneratedCodeTestHelper.AssertContainsAll(text,
            "namespace Demo\n{",
            "public partial struct Value;",
            "public interface IApi;",
            "[Flags]\n    public enum Mode : int",
            "None = 0,",
            "Read = 1,");
    }

    [Test]
    public void MethodCloneDeepCopiesAttributesAndParameters()
    {
        var method = new CSharpMethod("Compute")
        {
            ReturnType = CSharpPrimitiveType.Int(),
            Modifiers = CSharpModifiers.Static,
        };
        method.Attributes.Add(new CSharpFreeAttribute("MethodAttribute"));
        var parameter = new CSharpParameter(CSharpPrimitiveType.Int(), "value");
        parameter.Attributes.Add(new CSharpFreeAttribute("ParameterAttribute"));
        method.Parameters.Add(parameter);

        var clone = method.Clone();
        ((CSharpFreeAttribute)clone.Attributes[0]).Text = "ChangedMethodAttribute";
        clone.Parameters[0].Name = "changedValue";
        ((CSharpFreeAttribute)clone.Parameters[0].Attributes[0]).Text = "ChangedParameterAttribute";

        Assert.AreEqual("MethodAttribute", ((CSharpFreeAttribute)method.Attributes[0]).Text);
        Assert.AreEqual("value", method.Parameters[0].Name);
        Assert.AreEqual("ParameterAttribute", ((CSharpFreeAttribute)method.Parameters[0].Attributes[0]).Text);
        Assert.AreEqual("ChangedMethodAttribute", ((CSharpFreeAttribute)clone.Attributes[0]).Text);
        Assert.AreEqual("changedValue", clone.Parameters[0].Name);
        Assert.AreEqual("ChangedParameterAttribute", ((CSharpFreeAttribute)clone.Parameters[0].Attributes[0]).Text);
    }

    [Test]
    public void ToFunctionPointerMirrorsTypedParametersAndReturnType()
    {
        var method = new CSharpMethod("Callback")
        {
            ReturnType = CSharpPrimitiveType.Int(),
        };
        method.Parameters.Add(new CSharpParameter(CSharpPrimitiveType.Int(), "value"));
        method.Parameters.Add(new CSharpParameter("ignored"));

        var functionPointer = method.ToFunctionPointer();

        Assert.NotNull(functionPointer);
        Assert.AreEqual("delegate*<int, int>", GeneratedCodeTestHelper.DumpToString(functionPointer!));
        Assert.Null(new CSharpMethod("NoReturnType").ToFunctionPointer());
    }

    [Test]
    public void WrapCreatesPublicManagedMethodBeforeRenamedPrivateImport()
    {
        var owner = new CSharpClass("Native");
        var comment = new CSharpSimpleComment();
        var import = new CSharpMethod("Invoke")
        {
            Comment = comment,
            ReturnType = CSharpPrimitiveType.Void(),
            Modifiers = CSharpModifiers.Static | CSharpModifiers.Extern,
        };
        var dllImport = new CSharpDllImportAttribute("\"native\"");
        import.Attributes.Add(dllImport);
        owner.Members.Add(import);

        var wrapped = import.Wrap();

        Assert.AreEqual(2, owner.Members.Count);
        Assert.AreSame(wrapped, owner.Members[0]);
        Assert.AreSame(import, owner.Members[1]);
        Assert.AreEqual("Invoke", wrapped.Name);
        Assert.AreEqual(CSharpModifiers.Static, wrapped.Modifiers);
        Assert.AreSame(comment, wrapped.Comment);
        Assert.AreEqual("Invoke__", import.Name);
        Assert.AreEqual(CSharpVisibility.Private, import.Visibility);
        Assert.Null(import.Comment);
        Assert.AreEqual("\"Invoke\"", dllImport.EntryPoint);
    }
}
