name: ci

on:
  push:
    paths-ignore:
    - 'doc/**'
    - 'img/**'
    - 'readme.md'
  pull_request:

jobs:
  build:
    runs-on: 'windows-latest'
    steps:
      - name: "Build, Test, Pack and Publish"
        uses: xoofx/.github/.github/actions/dotnet-releaser-action@main
        with:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}